name: Build Keps

on:
  push:
  # schedule
  schedule:
  - cron: "0 1 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the keps
      run: pwsh ./create-keps.ps1

    - name: Cloudflare Pages GitHub Action
      # You may pin to the exact commit or the version.
      # uses: cloudflare/pages-action@752c4fc911d149221a4173136118c3cc250e9409
      uses: cloudflare/pages-action@v1.5.0
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: keps-ae5au-com
        directory: pub
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
